avia-develop/apps/admin_app/lib/admin_app_web/router.ex
defmodule AdminAppWeb.Router do
  use AdminAppWeb, :router
  use Plug.ErrorHandler
  use Sentry.Plug

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  # This pipeline is just to avoid CSRF token.
  # TODO: This needs to be remove when the token issue gets fixed in custom form
  pipeline :avoid_csrf do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:put_secure_browser_headers)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  pipeline :authentication do
    plug(AdminAppWeb.AuthenticationPipe)
  end

  scope "/", AdminAppWeb do
    # Use the default browser stack
    pipe_through([:browser, :authentication])

    get("/", PageController, :index)

    get("/orders/:category", OrderController, :index)
    get("/orders", OrderController, :index)
    get("/orders/:number/detail", OrderController, :show)
    put("/orders/:id/packages/", OrderController, :update_package, as: :order_package)
    put("/orders/:id/state", OrderController, :update_state, as: :order_state)
    put("/orders/:id/cod-payment", OrderController, :cod_payment_update, as: :order_cod_update)

    resources "/orders", OrderController, only: ~w[show create]a, param: "number" do
      get("/cart", OrderController, :get, as: :cart)
      post("/cart", OrderController, :remove_item, as: :cart)
      post("/cart/edit", OrderController, :edit, as: :cart)
      put("/cart/update", OrderController, :update_line_item, as: :cart)
      put("/cart", OrderController, :add, as: :cart)
      get("/address/search", OrderController, :address_search, as: :cart)
      put("/address/search", OrderController, :address_attach, as: :cart)
      get("/address/add", OrderController, :address_add_index, as: :cart)
      post("/address/add", OrderController, :address_add, as: :cart)
    end

    resources("/tax_categories", TaxCategoryController, only: [:index, :new, :create])
    resources("/stock_locations", StockLocationController)
    resources("/option_types", OptionTypeController)
    resources("/properties", PropertyController, except: [:show])
    resources("/registrations", RegistrationController, only: [:new, :create])
    resources("/session", SessionController, only: [:delete])
    resources("/users", UserController)
    resources("/roles", RoleController)
    resources("/permissions", PermissionController)
    resources("/variation_themes", VariationThemeController, except: [:show])
    resources("/prototypes", PrototypeController, except: [:show])
    resources("/products", ProductController)
    resources("/product_brands", ProductBrandController)
    resources("/payment_methods", PaymentMethodController)
    resources("/zones", ZoneController, only: [:index, :new, :create, :edit, :update, :delete])
    resources("/general_settings", GeneralSettingsController)
    post("/payment-provider-inputs", PaymentMethodController, :payment_preferences)
    get("/product/category", ProductController, :select_category)
    post("/product-images/:product_id", ProductController, :add_images)
    delete("/product-images/", ProductController, :delete_image)

    delete("/taxonomy/delete", TaxonomyController, :delete_taxonomy)
    resources("/taxonomy", TaxonomyController, except: [:update])
    post("/taxonomy/create", TaxonomyController, :create_taxonomy)

    get("/products/:product_id/property", ProductController, :index_property)
    get("/products/:product_id/property/new", ProductController, :new_property)
    get("/products/:product_id/property/:property_id/edit", ProductController, :edit_property)
    post("/products/:product_id/property/create", ProductController, :create_property)

    get("/dashboard", DashboardController, :index)

    post(
      "/products/:product_id/property/:property_id/update",
      ProductController,
      :update_property
    )

    delete(
      "/products/:product_id/property/:property_id/delete",
      ProductController,
      :delete_property
    )

    get("/shipping-policy/new", ShippingPolicyController, :new)
    get("/shipping-policy/:id/edit", ShippingPolicyController, :edit)
    put("/shipping-policy/:id", ShippingPolicyController, :update)
  end

  scope "/", AdminAppWeb do
    pipe_through(:avoid_csrf)
    post("/products/variants/new", ProductController, :new_variant)
    post("/product/stock", ProductController, :add_stock)
  end

  scope "/", AdminAppWeb do
    pipe_through(:browser)
    get("/orders/:number/show-invoice", OrderController, :show_invoice)
    get("/orders/:number/show-packing-slip", OrderController, :show_packing_slip)
    get("/orders/:number/download-packing-slip", OrderController, :download_packing_slip_pdf)
    get("/orders/:number/download-invoice", OrderController, :download_invoice_pdf)
    resources("/session", SessionController, only: [:new, :create, :edit, :update])
    get("/password_reset", SessionController, :password_reset)
    get("/password_recovery", SessionController, :verify)
    post("/check_email", SessionController, :check_email)
  end

  # Other scopes may use custom stacks.
  scope "/api", AdminAppWeb do
    pipe_through(:api)

    resources("/stock_locations", StockLocationController)
  end

  scope "/api", AdminAppWeb.TemplateApi do
    pipe_through(:api)

    resources("/option_types", OptionTypeController)
    get("/categories/:taxon_id", TaxonomyController, :index)
    get("/taxon/:taxon_id", TaxonomyController, :taxon_edit)
    put("/taxonomy/update", TaxonomyController, :update_taxon)
    post("/product_option_values/:id", OptionTypeController, :update)
  end
end

avia-develop/apps/admin_app/lib/admin_app_web/controllers/product_controller.ex
defmodule AdminAppWeb.ProductController do
  use AdminAppWeb, :controller

  alias Snitch.Core.Tools.MultiTenancy.Repo
  alias Snitch.Data.Model.Product, as: ProductModel
  alias Snitch.Data.Model
  alias Snitch.Data.Schema.Product, as: ProductSchema
  alias Snitch.Data.Model.ProductPrototype, as: PrototypeModel

  alias Snitch.Data.Schema.{
    ProductBrand,
    StockLocation,
    VariationTheme,
    ProductProperty,
    Property
  }

  alias Snitch.Tools.Money
  alias Snitch.Data.Model.StockItem, as: StockModel
  alias Snitch.Data.Schema.StockItem, as: StockSchema

  plug(:load_resources when action in [:new, :edit])

  @rummage_default %{
    "rummage" => %{
      "search" => %{
        "state" => %{"search_expr" => "where", "search_term" => "active", "search_type" => "eq"}
      },
      "sort" => %{"field" => "name", "order" => "asc"}
    }
  }

  def index(conn, params) do
    if params["rummage"] do
      products =
        ProductModel.get_rummage_product_list(params["rummage"])
        |> Repo.preload([:images, [variants: :images]])

      render(conn, "index.html", products: products)
    else
      redirect_with_updated_conn(conn, @rummage_default)
    end
  end

  def new(conn, _params) do
    changeset = ProductSchema.create_changeset(%ProductSchema{}, %{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"product" => params}) do
    with {:ok, product} <- ProductModel.create(params) do
      redirect(conn, to: product_path(conn, :edit, product.id))
    else
      {:error, changeset} ->
        render(conn, "new.html", changeset: %{changeset | action: :new})
    end
  end

  def edit(conn, %{"id" => id} = params) do
    preloads = [variants: [options: :option_type], images: [], taxon: [:variation_themes]]

    with %ProductSchema{} = product <- ProductModel.get(id) |> Repo.preload(preloads) do
      changeset = ProductSchema.create_changeset(product, params)
      render(conn, "edit.html", changeset: changeset, parent_product: product)
    end
  end

  def update(conn, %{"product" => params}) do
    with %ProductSchema{} = product <- ProductModel.get(params["id"]),
         {:ok, _product} <- ProductModel.update(product, params) do
      redirect_with_updated_conn(conn, params)
    end
  end

  def add_images(conn, %{"product_images" => product_images, "product_id" => id}) do
    product =
      id
      |> String.to_integer()
      |> ProductModel.get()
      |> Repo.preload(:images)

    images = (product_images["images"] ++ product.images) |> parse_images()

    params = %{"images" => images}

    case ProductModel.add_images(product, params) do
      {:ok, _} ->
        redirect(conn, to: product_path(conn, :index))

      {:error, _} ->
        redirect(conn, to: product_path(conn, :index))
    end
  end

  def delete_image(conn, %{"image_id" => image_id, "product_id" => product_id}) do
    image_id = String.to_integer(image_id)
    product_id = String.to_integer(product_id)

    case ProductModel.delete_image(product_id, image_id) do
      {:ok, _} ->
        conn
        |> put_status(200)
        |> json(%{data: "success"})

      {:error, reason} ->
        conn
        |> put_status(500)
        |> json(%{data: reason})
    end
  end

  defp parse_images(image_list) do
    Enum.reduce(image_list, [], fn
      %Plug.Upload{} = image, acc ->
        [%{"image" => image} | acc]

      image, acc ->
        %{id: id, name: name} = Map.from_struct(image)
        [%{"id" => id, "name" => name} | acc]
    end)
  end

  def delete(conn, %{"id" => id}) do
    with {:ok, _product} <- ProductModel.delete(id) do
      conn
      |> put_flash(:info, "Product deleted successfully")
      |> redirect(to: product_path(conn, :index))
    end
  end

  def new_variant(conn, params) do
    with %ProductSchema{} = parent_product <- ProductModel.get(params["product_id"]),
         variant_params <- generate_variant_params(parent_product, params["options"]),
         %Ecto.Changeset{valid?: true} = changeset <-
           ProductSchema.variant_create_changeset(parent_product, %{
             "variations" => variant_params,
             "theme_id" => params["theme_id"]
           }) do
      {:ok, _product} = Repo.update(changeset)
      redirect(conn, to: product_path(conn, :index))
    else
      _ ->
        conn
        |> put_flash(:error, "Failed to create variant")
        |> redirect(to: product_path(conn, :index))
    end
  end

  def select_category(conn, _params) do
    render(conn, "product_category.html")
  end

  def add_stock(conn, %{"stock" => params}) do
    with {:ok, stock} <- check_stock(params["product_id"], params["location_id"]),
         {:ok, _updated_stock} <- StockModel.update(params, stock) do
      redirect(conn, to: product_path(conn, :index))
    end
  end

  defp check_stock(product_id, location_id) do
    query_fields = %{product_id: product_id, stock_location_id: location_id}

    case StockModel.get(query_fields) do
      %StockSchema{} = stock_item -> {:ok, stock_item}
      nil -> StockModel.create(product_id, location_id, 0, false)
    end
  end

  def generate_variant_params(parent_product, options) do
    options =
      options
      |> Map.to_list()
      |> Enum.map(fn {_index, map} ->
        map["value"]
        |> String.trim()
        |> String.split(",")
        |> Enum.map(fn option_value ->
          %{option_type_id: map["option_type_id"], value: option_value}
        end)
      end)

    generate_option_combinations(options, [])
    |> Enum.map(fn options ->
      %{
        "child_product" => %{
          name: product_name_from_options(parent_product, options),
          options: options,
          selling_price: parent_product.selling_price,
          max_retail_price: parent_product.max_retail_price,
          taxon_id: parent_product.taxon_id,
          shipping_category_id: parent_product.shipping_category_id
        }
      }
    end)
  end

  defp product_name_from_options(product, options) do
    options
    |> Enum.reduce(product.name, fn x, acc -> "#{acc} #{x.value}" end)
  end

  def generate_option_combinations([head | tail], []) do
    acc =
      head
      |> Enum.map(&[&1])

    generate_option_combinations(tail, acc)
  end

  def generate_option_combinations([], acc) do
    acc
  end

  def generate_option_combinations([head | tail], acc) do
    result =
      acc
      |> Enum.flat_map(fn v ->
        head
        |> Enum.map(fn x -> v ++ [x] end)
      end)

    generate_option_combinations(tail, result)
  end

  def load_resources(conn, _opts) do
    load(conn, conn.params)
  end

  defp load(conn, _params) do
    themes = Repo.all(VariationTheme)

    brands = Repo.all(ProductBrand)

    stock_locations = Repo.all(StockLocation)

    conn
    |> assign(:themes, themes)
    |> assign(:stock_locations, stock_locations)
    |> assign(:brands, brands)

    # |> assign(:prototype, prototype)
  end

  defp redirect_with_updated_conn(conn, params) do
    updated_conn =
      conn
      |> Map.put(:query_params, params)
      |> Map.put(:query_string, Plug.Conn.Query.encode(params))

    redirect(updated_conn, to: product_path(updated_conn, :index, params))
  end

  def index_property(conn, _params) do
    render(conn, "property_index.html")
  end

  def new_property(conn, params) do
    changeset =
      ProductProperty.create_changeset(%ProductProperty{}, %{product_id: params["product_id"]})

    render(conn, "property_new.html",
      conn: conn,
      changeset: changeset,
      product_id: params["product_id"]
    )
  end

  def create_property(conn, params) do
    with %ProductSchema{} = _product <- ProductModel.get(params["product_id"]),
         %Property{} = _property <- Model.Property.get(params["product_property"]["property_id"]),
         {:ok, _product_property} <- Model.ProductProperty.create(params["product_property"]) do
      redirect(conn, to: product_path(conn, :edit, params["product_id"]))
    else
      {:error, changeset} ->
        render(conn, "property_new.html", changeset: changeset)
    end
  end

  def edit_property(conn, params) do
    changeset = ProductProperty.update_changeset(%ProductProperty{}, params)
    render(conn, "property_edit.html", changeset: changeset, conn: conn)
  end

  def update_property(conn, params) do
    with %ProductProperty{} = product_property <-
           Model.ProductProperty.get_by(%{
             product_id: params["product_property"]["product_id"],
             property_id: params["product_property"]["property_id"]
           }),
         {:ok, _} = Model.ProductProperty.update(product_property, params["product_property"]) do
      redirect(conn, to: product_path(conn, :edit, params["product_property"]["product_id"]))
    else
      {:error, changeset} ->
        render(conn, "property_edit.html", changeset: changeset, conn: conn)
    end
  end

  def delete_property(conn, params) do
    with %ProductProperty{} = product_property <-
           Model.ProductProperty.get_by(%{
             product_id: params["product_id"],
             property_id: params["property_id"]
           }),
         {:ok, _} <- Model.ProductProperty.delete(product_property) do
      conn
      |> put_flash(:info, "Product property deleted successfully")

      redirect(conn, to: product_path(conn, :edit, params["product_id"]))
    end
  end
end

avia-develop/apps/admin_app/lib/admin_app_web/templates/product/edit.html.eex
<div class="list-container">
  <div class="pt-3 pb-0 pr-3 pl-3 back"> <img src="/images/left-arrow.svg"
   width="20" height="20" class="d-inline-block align-top" alt="">
   <a href="/products">Product</a> </div>
  <h4 class="p-3 m-0">Edit a product</h4>
  <div class="col-12">
    <div class="card col-12">
      <%= render "form.html",
            changeset: @changeset,
            conn: @conn,
            action: product_path(@conn, :update, @changeset.data),
            parent_product: @parent_product,
            brands: @brands,
            stock_locations: @stock_locations,
            themes: @themes
        %>
    </div>
  <div>
</div>

avia-develop/apps/admin_app/lib/admin_app_web/templates/product/form.html.eex
<ul class="nav nav-tabs">
   <li class="nav-item">
      <a class="nav-link active" href="#tab1default" data-toggle="tab">Product Detail</a>
   </li>
   <%= if  @conn.request_path != product_path(@conn, :new) do %>
   <%= if can_add_variant(@parent_product) do %>
    <li class="nav-item">
        <a class="nav-link" href="#tab2default" data-toggle="tab">Variants</a>
    </li>
   <% end %>
   <li class="nav-item">
      <a class="nav-link" href="#tab3default" data-toggle="tab">Images</a>
   </li>
   <li class="nav-item">
      <a class="nav-link" href="#tab4default" data-toggle="tab">Stock</a>
   </li>
   <li class="nav-item">
      <a class="nav-link" href="#tab5default" data-toggle="tab">Properties</a>
   </li>
   <% end %>
</ul>
<div class="tab-content ">
  <div class="tab-pane p-3 fade in active show p-3" id="tab1default">
    <%= form_for @changeset, @action, [multipart: true], fn f ->  %>
    <%= hidden_input f, :id %>
    <%= if  @conn.request_path == product_path(@conn, :new) do %>
    <%= hidden_input :taxon_id, :taxon_id, value: get_taxon(@conn), name: "product[taxon_id]" %>
    <% end %>
    <div class="form-group row ">
      <%= input f, :name, "Title", is_horizontal: true, description: "Include keywords that buyers would use to search for your item." %>
    </div>
    <div class="form-group row ">
      <%= textarea_input f, :description, nil, is_horizontal: true, description: "
        Start with a brief overview that describes your item's finest features.List details like dimensions and key features in easy-to-read bullet points.Tell buyers a bit about your process or the story behind this item.", rows: "10" %>
    </div>
    <div class="form-group row ">
      <label  class="col-sm-3 col-form-label">
        <div class="label">
          Selling Price
        </div>
        <div class="label-txt">The price at which product is being currently sold(After any promotional discounts).</div>
      </label>
      <div class="col-sm-9 input-group">
        <%= text_input :selling_price, :amount, value: get_amount(f.data.selling_price), class: "form-control", name: "product[selling_price][amount]" %>
        <div class="input-group-append">
          <%= select :selling_price, :currency, get_currency(),value: get_currency_value(f.data.selling_price), class: "form-control", name: "product[selling_price][currency]" %>
        </div>
      </div>
    </div>
    <div class="form-group row ">
      <label  class="col-sm-3 col-form-label">
        <div class="label">
          Maximum Retail Price
        </div>
        <div class="label-txt">The original cost of the product.</div>
      </label>
      <div class="col-sm-9 input-group">
        <%= text_input :max_retail_price, :amount, value: get_amount(f.data.max_retail_price), class: "form-control", name: "product[max_retail_price][amount]" %>
        <div class="input-group-append">
          <%= select :max_retail_price, :currency, get_currency(),value: get_currency_value(f.data.max_retail_price), class: "form-control", name: "product[max_retail_price][currency]" %>
        </div>
      </div>
    </div>
    <div class="form-group row ">
      <%= select_input f, :shipping_category_id, get_shipping_category(), nil, is_horizontal: true, description: "Select appropriate shipping method for the product eg. Heavy for Washing Machine, Light for T-shirt." %>
    </div>
    <div class="form-group row ">
      <%= select_input f, :brand_id, get_brand_options(@brands), nil, is_horizontal: true, description: "Select branch of the product Eg. Levi's." %>
    </div>
    <div class="form-group row ">
      <%= input f, :meta_title_, nil, is_horizontal: true, description: "A short title which helps improve the SEO of the product." %>
    </div>
    <div class="form-group row ">
      <%= textarea_input f, :meta_description, nil, is_horizontal: true, description: "Meta description is the short text which helps to improve SEO of the product." %>
    </div>
    <div class="form-group row ">
      <%= input f, :meta_keywords, nil, is_horizontal: true, description: "Meta keywords are tags which helps to improve SEO of the product." %>
    </div>
    <div class="form-group row ">
      <%= input f, :height, nil, is_horizontal: true, description: "Specifies height of the product." %>
    </div>
    <div class="form-group row ">
      <%= input f, :width, nil, is_horizontal: true, description: "Specifies width of the product." %>
    </div>
    <div class="form-group row ">
      <%= input f, :depth, nil, is_horizontal: true, description: "Specifies depth of the product." %>
    </div>
    <div class="form-group row ">
      <%= input f, :weight, nil, is_horizontal: true, description: "Specifies weight of the product." %>
    </div>
    <div class="form-group row stickformbutton">
      <div class="col-sm-10">
        <%= button("Cancel", to: product_path(@conn, :index), method: "get",
          class: "btn btn-secondary btn-outline-secondary submit-btn float-left") %>
        <%= submit "Submit", class: "btn  btn-primary submit-btn float-right" %>
      </div>
    </div>
    <% end %>
  </div>
  <%= if  @conn.request_path != product_path(@conn, :new) and can_add_variant(@parent_product) do %>
  <div class="tab-pane fade p-3
  " id="tab2default" >
    <div style="background: #f8f9fa;">
      <div class="form-group required">
        <label>Variation Theme</label>
        <%= select :theme, :theme_id, themes_options(@parent_product), selected: @parent_product.theme_id ,prompt: "", class: "form-control", id: "product_theme_id" %>
      </div>
      <div id="variation_options" style="padding: 10px 0px 10px 0px;"></div>
      <div class="modal fade" id="theme_change_modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLongTitle">Warning</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <div class="alert alert-danger" role="alert">
                Changing theme will remove all the associated variants.
                Are you sure you want to do this?
              </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
              <button id="theme_change_confirm" type="button" class="btn btn-primary">Yes</button>
            </div>
          </div>
        </div>
      </div>
    </div>
    <%= if has_variants(@parent_product) do %>
    <div>
      <h3>Product Variants</h3>
      <table class="table">
        <thead>
          <tr>
            <th>Product ID</th>
            <%= for option_type <- get_option_types(@parent_product) do %>
            <th><%= option_type.display_name %></th>
            <% end %>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <%= for variant <- @parent_product.variants do %>
          <tr>
            <td><%= variant.id %></td>
            <%= for option <- variant.options do %>
            <td class="option-value" contenteditable="true" data-option_value_id="<%= option.id %>"><%= option.value %></td>
            <% end %>
            <td>
              <%= link("Edit", to: product_path(@conn, :edit, variant.id), class: "btn btn-primary") %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <% end %>
  </div>
  <% end %>
  <%= if  @conn.request_path != product_path(@conn, :new) do %>
  <div class="tab-pane fade p-3" id="tab3default">
    <div>
      <input id="product-id" name="product-id" type="hidden" value="<%= @parent_product.id %>" >
      <%= form_for @conn, product_path(@conn, :add_images, @parent_product.id),
        [as: :product_images, multipart: true], fn f -> %>
      <div class="form-group row ">
        <label  class="col-sm-3 col-form-label">
          <div class="label required">
            Images
          </div>
          <div class="label-txt">Include keywords that buyers would use to search for your item.</div>
        </label>
        <div class="col-sm-9">
          <div class="row imgcol">
            <%= if length(@parent_product.images) > 0 do %>
            <%= for image <- @parent_product.images do %>
            <div class="img-wrap col-3 p-1">
              <span class="product-delete">&times;
              <input name="delete-image-id" type="hidden" value="<%= image.id %>" >
              </span>
              <%= img_tag(get_image_url(image, @parent_product), class: "img-thumbnail") %>
            </div>
            <% end %>
            <% end %>
            <div class="file-upload col-3 p-1">
              <label for="upload" class="file-upload__label">
                <div><i class="fas fa-camera"></i></div>
                <div>Add Images</div>
              </label>
              <%= file_input f, :images, multiple: true, class: "file-upload__input",
                id: "product-images" %>
            </div>
            <div id="img-selected-container" class="img-selected-container row m-0 col-12 p-0">
            </div>
          </div>
        </div>
      </div>
      <div class="form-group row stickformbutton">
        <div class="col-sm-10">
          <%= button("Cancel", to: product_path(@conn, :index), method: "get",
            class: "btn btn-secondary btn-outline-secondary submit-btn float-left") %>
          <%= submit "Submit", class: "btn  btn-primary submit-btn float-right" %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
  <% end %>
  <%= if  @conn.request_path != product_path(@conn, :new) do %>
  <div class="tab-pane fade pt-2 p-3"  id="tab4default">
    <form accept-charset="UTF-8" action="/product/stock" method="post">
      <%= if is_parent_product(@conn.params["id"]) do %>
      <div class="form-group required">
        <label>Variant</label>
        <%= select :stock, :product_id, get_variant_option(@parent_product.variants), class: "form-control"%>
      </div>
      <% else %>
      <%= hidden_input :stock, :product_id, value: @conn.params["id"] %>
      <% end %>

      <div class="form-group row ">
        <label  class="col-sm-3 col-form-label">
          <div class="label required">
            Count on hand
          </div>
          <div class="label-txt">Total count for all the products at all stock locations</div>
          <div class="col-sm-9">
            <p><%= count_on_hand(@conn) %></p>
          </div>
        </label>
      </div>

      <div class="form-group row ">
        <label  class="col-sm-3 col-form-label">
          <div class="label required">
            Stock Location
          </div>
          <div class="label-txt">Include keywords that buyers would use to search for your item.</div>
        </label>
        <div class="col-sm-9">
          <%= select :stock, :location_id, get_stock_locations_option(@stock_locations), class: "form-control"%>
        </div>
      </div>
      <div class="form-group row ">
        <label  class="col-sm-3 col-form-label">
          <div class="label required">
            Count
          </div>
          <div class="label-txt">Include keywords that buyers would use to search for your item.</div>
        </label>
        <div class="col-sm-9">
          <%= text_input :stock, :count_on_hand , class: "form-control"%>
        </div>
      </div>
      <div class="form-group row stickformbutton">
        <div class="col-sm-10">
          <button class="btn btn-primary submit-btn float-right" type="submit">Add Stock</button>
          <%= button("Cancel", to: product_path(@conn, :index), method: "get",
            class: "btn btn-secondary btn-outline-secondary submit-btn float-left") %>
        </div>
      </div>
    </form>
  </div>
  <% end %>
  <%= if  @conn.request_path != product_path(@conn, :new) do %>
    <div class="tab-pane fade pt-2"  id="tab5default">
      <%= render "property_index.html",
              conn: @conn
          %>
    </div>
  <% end %>
</div>
<html>
  <head>
    <%= csrf_meta_tag %>
  </head>
</html>

avia-develop/apps/admin_app/lib/admin_app_web/templates/product/new.html.eex
<div class="list-container">
  <div class="pt-3 pb-0 pr-3 pl-3 back"> <img src="/images/left-arrow.svg"
    width="20" height="20" class="d-inline-block align-top" alt="">
    <a href="/products">Product</a>
  </div>
  <h4 class="p-3 m-0">Add a product</h4>
  <div class="col-12">
    <div class="card col-12">
      <%= render "form.html",
        changeset: @changeset,
        conn: @conn,
        action: product_path(@conn, :create),
        brands: @brands
        %>
    </div>
  </div>
</div>

avia-develop/apps/admin_app/lib/admin_app_web/templates/product/product_category.html.eex
<div class="list-container">
  <div class="row m-0 list-header">
    <div class="col-10 p-0">
      <h2>Select product category</h2>
    </div>   
  </div>
  <div class="row m-0 list">
    <div class="table-contaner col-12 p-0">
      <section id="category_selection" class="card1"></section>
      <div id="category_loader" class="loader"></div>
    </div>
  </div>
</div>