avia-develop/apps/admin_app/lib/admin_app_web/router.ex
defmodule AdminAppWeb.Router do
  use AdminAppWeb, :router
  use Plug.ErrorHandler
  use Sentry.Plug

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  # This pipeline is just to avoid CSRF token.
  # TODO: This needs to be remove when the token issue gets fixed in custom form
  pipeline :avoid_csrf do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:put_secure_browser_headers)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  pipeline :authentication do
    plug(AdminAppWeb.AuthenticationPipe)
  end

  scope "/", AdminAppWeb do
    # Use the default browser stack
    pipe_through([:browser, :authentication])

    get("/", PageController, :index)

    get("/orders/:category", OrderController, :index)
    get("/orders", OrderController, :index)
    get("/orders/:number/detail", OrderController, :show)
    put("/orders/:id/packages/", OrderController, :update_package, as: :order_package)
    put("/orders/:id/state", OrderController, :update_state, as: :order_state)
    put("/orders/:id/cod-payment", OrderController, :cod_payment_update, as: :order_cod_update)

    resources "/orders", OrderController, only: ~w[show create]a, param: "number" do
      get("/cart", OrderController, :get, as: :cart)
      post("/cart", OrderController, :remove_item, as: :cart)
      post("/cart/edit", OrderController, :edit, as: :cart)
      put("/cart/update", OrderController, :update_line_item, as: :cart)
      put("/cart", OrderController, :add, as: :cart)
      get("/address/search", OrderController, :address_search, as: :cart)
      put("/address/search", OrderController, :address_attach, as: :cart)
      get("/address/add", OrderController, :address_add_index, as: :cart)
      post("/address/add", OrderController, :address_add, as: :cart)
    end

    resources("/tax_categories", TaxCategoryController, only: [:index, :new, :create])
    resources("/stock_locations", StockLocationController)
    resources("/option_types", OptionTypeController)
    resources("/properties", PropertyController, except: [:show])
    resources("/registrations", RegistrationController, only: [:new, :create])
    resources("/session", SessionController, only: [:delete])
    resources("/users", UserController)
    resources("/roles", RoleController)
    resources("/permissions", PermissionController)
    resources("/variation_themes", VariationThemeController, except: [:show])
    resources("/prototypes", PrototypeController, except: [:show])
    resources("/products", ProductController)
    resources("/product_brands", ProductBrandController)
    resources("/payment_methods", PaymentMethodController)
    resources("/zones", ZoneController, only: [:index, :new, :create, :edit, :update, :delete])
    resources("/general_settings", GeneralSettingsController)
    post("/payment-provider-inputs", PaymentMethodController, :payment_preferences)
    get("/product/category", ProductController, :select_category)
    post("/product-images/:product_id", ProductController, :add_images)
    delete("/product-images/", ProductController, :delete_image)

    delete("/taxonomy/delete", TaxonomyController, :delete_taxonomy)
    resources("/taxonomy", TaxonomyController, except: [:update])
    post("/taxonomy/create", TaxonomyController, :create_taxonomy)

    get("/products/:product_id/property", ProductController, :index_property)
    get("/products/:product_id/property/new", ProductController, :new_property)
    get("/products/:product_id/property/:property_id/edit", ProductController, :edit_property)
    post("/products/:product_id/property/create", ProductController, :create_property)

    get("/dashboard", DashboardController, :index)

    post(
      "/products/:product_id/property/:property_id/update",
      ProductController,
      :update_property
    )

    delete(
      "/products/:product_id/property/:property_id/delete",
      ProductController,
      :delete_property
    )

    get("/shipping-policy/new", ShippingPolicyController, :new)
    get("/shipping-policy/:id/edit", ShippingPolicyController, :edit)
    put("/shipping-policy/:id", ShippingPolicyController, :update)
  end

  scope "/", AdminAppWeb do
    pipe_through(:avoid_csrf)
    post("/products/variants/new", ProductController, :new_variant)
    post("/product/stock", ProductController, :add_stock)
  end

  scope "/", AdminAppWeb do
    pipe_through(:browser)
    get("/orders/:number/show-invoice", OrderController, :show_invoice)
    get("/orders/:number/show-packing-slip", OrderController, :show_packing_slip)
    get("/orders/:number/download-packing-slip", OrderController, :download_packing_slip_pdf)
    get("/orders/:number/download-invoice", OrderController, :download_invoice_pdf)
    resources("/session", SessionController, only: [:new, :create, :edit, :update])
    get("/password_reset", SessionController, :password_reset)
    get("/password_recovery", SessionController, :verify)
    post("/check_email", SessionController, :check_email)
  end

  # Other scopes may use custom stacks.
  scope "/api", AdminAppWeb do
    pipe_through(:api)

    resources("/stock_locations", StockLocationController)
  end

  scope "/api", AdminAppWeb.TemplateApi do
    pipe_through(:api)

    resources("/option_types", OptionTypeController)
    get("/categories/:taxon_id", TaxonomyController, :index)
    get("/taxon/:taxon_id", TaxonomyController, :taxon_edit)
    put("/taxonomy/update", TaxonomyController, :update_taxon)
    post("/product_option_values/:id", OptionTypeController, :update)
  end
end

avia-develop/apps/admin_app/lib/admin_app/order/package.ex
defmodule AdminApp.PackageContext do
  import Ecto.Query
  alias Snitch.Data.Schema.Package
  alias Snitch.Core.Tools.MultiTenancy.Repo

  def update_packages(state, order_id) do
    query =
      from(
        package in Package,
        where: package.order_id == ^order_id
      )

    case Repo.update_all(query, set: [state: state]) do
      {0, _} ->
        {:error, "Update failed"}

      _ ->
        {:ok, "updated"}
    end
  end
end

avia-develop/apps/admin_app/lib/admin_app_web/controllers/order_controller.ex
defmodule AdminAppWeb.OrderController do
  use AdminAppWeb, :controller

  import Ecto.Query
  import Phoenix.View, only: [render_to_string: 3]

  alias Snitch.Data.Model.Order
  alias BeepBop.Context
  alias Snitch.Domain.Order.DefaultMachine
  alias Snitch.Data.Schema.{Address, Product}
  alias Snitch.Core.Tools.MultiTenancy.Repo
  alias AdminAppWeb.OrderView
  alias AdminApp.OrderContext
  alias AdminApp.PackageContext

  @root_path [File.cwd!(), "invoices"] |> Path.join()

  def index(conn, %{"category" => category}) do
    sort_param = conn.query_params["sort"]
    orders = OrderContext.order_list(category, sort_param)
    token = get_csrf_token()

    html =
      render_to_string(
        OrderView,
        "order_listing.html",
        orders: orders,
        token: token
      )

    conn
    |> put_status(200)
    |> json(%{html: html})
  end

  def index(conn, _params) do
    render(conn, "index.html", %{
      orders: OrderContext.order_list("pending", nil),
      token: get_csrf_token()
    })
  end

  def show(conn, %{"number" => _number} = params) do
    order = OrderContext.get_order(params)
    order_total = OrderContext.get_total(order)

    render(
      conn,
      "show.html",
      order: order,
      order_total: order_total
    )
  end

  def update_package(conn, %{"id" => id, "state" => state}) do
    order = OrderContext.get_order(%{"id" => id})

    case PackageContext.update_packages(state, String.to_integer(id)) do
      {:ok, _} ->
        order_total = OrderContext.get_total(order)

        conn
        |> put_flash(:info, "Order Updated!")
        |> render("show.html", order: order, order_total: order_total)

      {:error, _} ->
        put_flash(conn, :error, "update failed!")
        redirect(conn, to: order_path(conn, :show, order.number))
    end
  end

  def update_state(conn, %{"id" => id, "state" => state}) do
    order = OrderContext.get_order(%{"id" => id})

    case OrderContext.state_transition(state, order) do
      {:ok, message} ->
        conn
        |> put_flash(:info, message)
        |> redirect(to: order_path(conn, :show, order.number))

      {:error, message} ->
        conn
        |> put_flash(:error, message)
        |> redirect(to: order_path(conn, :show, order.number))
    end
  end

  def cod_payment_update(conn, %{"id" => id, "state" => state}) do
    order = OrderContext.get_order(%{"id" => id})

    case OrderContext.update_cod_payment(order, state) do
      {:ok, _} ->
        conn
        |> put_flash(:info, "Order Payment marked as #{state}")
        |> redirect(to: order_path(conn, :show, order.number))

      {:error, _} ->
        conn
        |> put_flash(:error, "Update failed!")
        |> redirect(to: order_path(conn, :show, order.number))
    end
  end

  def create(conn, _params) do
    current_user = Guardian.Plug.current_resource(conn)
    {:ok, order} = Order.create(%{line_items: [], user_id: current_user.id})

    redirect(conn, to: order_path(conn, :show, order.id))
  end

  def show_invoice(conn, params) do
    order =
      load_order(%{number: params["number"]})
      |> Repo.preload([:line_items, :user])

    render(conn, "invoice.html", %{order: order})
  end

  def show_packing_slip(conn, params) do
    order = load_order(%{number: params["number"]})

    render(conn, "packing_slip.html", %{order: order})
  end

  def download_invoice_pdf(conn, params) do
    order = load_order(%{number: params["number"]})
    download_pdf_response(conn, order, "invoice", params)
  end

  def download_packing_slip_pdf(conn, params) do
    order = load_order(%{number: params["number"]})
    download_pdf_response(conn, order, "packing_slip", params)
  end

  def edit(conn, params) do
    order = load_order(%{number: params["order_number"]})

    update_item =
      fetch_line_item(params["update"], order.line_items)
      |> List.first()

    render(conn, "edit.html", %{order: order, search: [], update_item: update_item})
  end

  def update_line_item(conn, params) do
    order = load_order(%{number: params["order_number"]})

    update_item = params["update"]
    line_items = remove_line_item(update_item, order.line_items)
    update_item = List.first(fetch_line_item(update_item, order.line_items))
    updated_list = [%{quantity: params["quantity"], id: update_item.id} | line_items || []]

    case Order.update(%{line_items: updated_list}, order) do
      {:ok, order} ->
        redirect(conn, to: order_path(conn, :show, order.id))

      {:error, error} ->
        %{errors: [line_items: {error_text, _}]} = error
        conn = put_flash(conn, :error, error_text)
        redirect(conn, to: order_path(conn, :show, order.id))
    end

    render(conn, "edit.html", %{order: order, search: [], update_item: update_item})
  end

  def add(conn, params) do
    order = load_order(%{number: params["order_number"]})

    product_id = String.to_integer(params["add"])
    quantity = String.to_integer(params["quantity"])
    add_line_item = %{quantity: quantity, product_id: product_id}
    new_item_list = [add_line_item | struct_to_map(order.line_items)]

    case Order.update(%{line_items: new_item_list}, order) do
      {:ok, order} ->
        redirect(conn, to: order_path(conn, :show, order.id))

      {:error, error} ->
        %{errors: [line_items: {error_text, _}]} = error
        conn = put_flash(conn, :error, error_text)
        redirect(conn, to: order_path(conn, :show, order.id))
    end
  end

  def remove_item(conn, params) do
    order = load_order(%{number: params["order_number"]})

    edit_item = params["edit"]
    line_items = remove_line_item(edit_item, order.line_items)

    {:ok, order} =
      Order.update(
        %{
          line_items: line_items
        },
        order
      )

    redirect(conn, to: order_path(conn, :show, order.id))
  end

  def address_add_index(conn, params) do
    order = load_order(%{number: params["order_number"]})

    render(conn, "address_add.html", %{order: order})
  end

  def address_search(conn, params) do
    order = load_order(%{number: params["order_number"]})
    address_list = search_address_list(params["address_search"])

    case address_list do
      [] ->
        render(conn, "address_search.html", %{order: order, address_list: []})

      address_list ->
        render(conn, "address_search.html", %{order: order, address_list: address_list})
    end
  end

  def address_attach(conn, params) do
    order = load_order(%{number: params["order_number"]})
    address_id = String.to_integer(params["address_id"])

    address =
      Repo.get(Address, address_id)
      |> Map.from_struct()
      |> Map.drop([:__meta])

    context =
      order
      |> Context.new(
        state: %{
          billing_address: address,
          shipping_address: address
        }
      )

    transition = DefaultMachine.add_addresses(context)

    case transition.valid? do
      true ->
        redirect(conn, to: order_path(conn, :show, order.id))

      false ->
        conn = put_flash(conn, :error, transition.errors[:error])
        redirect(conn, to: "/orders/#{order.number}/address/search")
    end
  end

  def address_add(conn, params) do
    order = load_order(%{number: params["order_number"]})

    changeset = Address.changeset(%Address{}, params["address"])

    case changeset.valid? do
      true ->
        {:ok, address} = Repo.insert(changeset)
        redirect(conn, to: "/orders/#{order.number}/address/search")

      false ->
        [error_text | _] = changeset.errors
        {title, {error_value, _}} = error_text
        conn = put_flash(conn, :error, Atom.to_string(title) <> " - " <> error_value)
        redirect(conn, to: "/orders/#{order.number}/address/add")
    end
  end

  defp remove_line_item(edit_item, line_items) do
    line_items
    |> Enum.reject(fn %{id: id} -> id == String.to_integer(edit_item) end)
    |> Enum.map(fn item -> Map.from_struct(item) |> Map.drop([:__meta]) end)
  end

  defp fetch_line_item(edit_item, line_items) do
    line_items
    |> Enum.reject(fn %{id: id} -> id != String.to_integer(edit_item) end)
  end

  defp struct_to_map(items) do
    Enum.map(items, fn item -> Map.from_struct(item) |> Map.drop([:__meta]) end)
  end

  defp search_item_variant(search) do
    query =
      from(
        u in Product,
        where: ilike(u.sku, ^"%#{search}%")
      )

    Repo.all(query)
  end

  defp search_address_list(search) do
    query =
      from(
        u in Address,
        where: ilike(u.first_name, ^"%#{search}%")
      )

    Repo.all(query)
  end

  defp load_order(order) do
    order
    |> Order.get()
    |> Repo.preload([
      [line_items: :product],
      [packages: [:items, :shipping_method]],
      :payments,
      :user
    ])
  end

  defp download_pdf_response(conn, order, type, params) do
    case generate_pdf(order, type) do
      {:ok, :ok} ->
        send_file_response(
          conn,
          params,
          @root_path |> Path.join("#{type}_#{params["number"]}.pdf"),
          type
        )

      {:ok, {:error, reason}} ->
        send_pdf_response(conn, params, {:error, reason |> format_error()}, type)

      {:error, message} ->
        send_pdf_response(conn, params, {:error, message}, type)
    end
  end

  defp send_file_response(conn, params, path, type) do
    case read_file(path) do
      {:ok, file} ->
        send_pdf_response(conn, params, {:ok, file}, type)

      {:error, reason} ->
        send_pdf_response(conn, params, {:error, reason |> format_error()}, type)
    end
  end

  defp send_pdf_response(conn, params, {:error, msg}, _type) do
    conn
    |> put_flash(:error, msg)
    |> redirect(to: "/orders/#{params["number"]}/detail")
  end

  defp send_pdf_response(conn, params, {:ok, data}, type) do
    conn
    |> put_resp_content_type("application/pdf")
    |> put_resp_header(
      "content-disposition",
      "attachment; filename=\"#{type}_#{params["number"]}.pdf\""
    )
    |> send_resp(200, data)
  end

avia-develop/apps/admin_app/lib/admin_app_web/templates/order/address_add.html.eex
<div class="container">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="/orders">Orders</a></li>
      <li class="breadcrumb-item active" aria-current="page"><%= @order.number %></li>
    </ol>
  </nav>

  <h2>
    Order #<%= @order.id %>
    <%= state_badge(@order.state) %>
  </h2>
  <div class="row">
    <div class="col-8">
      <!-- The real deal  -->
      <div class="card">
        <h3>Add Address </h3>
        <div class="card-body">
          <form action=<%= "/orders/#{@order.number}/address" %> method="post">
            <div class="panel-body">

  <div class="form-group billing-row field" id=": _firstname_field">
    <label for="order_address_attributes_firstname">First Name</label>
    <input class="form-control" name="address[first_name]" id="order_address_attributes_firstname" type="text">

</div>
  <div class="form-group billing-row field">
    <label for="order_address_attributes_lastname">Last Name</label>
    <input class="form-control" name="address[last_name]" id="order_address_attributes_lastname" type="text">

</div>

  <div class="form-group billing-row field">
    <label for="order_address_attributes_address1">Street Address</label>
    <input class="form-control" name="address[address_line_1]" id="order_address_attributes_address1" type="text">

</div>
  <div class="form-group billing-row field">
    <label for="order_address_attributes_address2">Street Address (cont'd)</label>
    <input class="form-control" name="address[address_line_2]" id="order_address_attributes_address2" type="text">

</div>
  <div class="form-group billing-row field">
    <label for="order_address_attributes_city">City</label>
    <input class="form-control" name="address[city]" id="order_address_attributes_city" type="text">

</div>
  <div class="form-group billing-row field">
    <label for="order_address_attributes_zipcode">Zip</label>
    <input class="form-control" name="address[zip_code]" id="order_address_attributes_zipcode" type="text">
</div>

</div>
  <div class="form-group billing-row field">
    <label for="order_address_attributes_phone">Phone</label>
    <input class="form-control" name="address[phone]" id="order_address_attributes_phone" type="tel">
  </div>

  <div class="form-group billing-row field">
    <label for="order_address_attributes_phone">State</label>
    <input class="form-control" name="address[state_id]" id="order_address_attributes_state" type="text">
  </div>
  <div class="form-group billing-row field">
    <label for="order_address_attributes_phone">Country</label>
    <input class="form-control" name="address[country_id]" id="order_address_attributes_country" type="text">
  </div>
<button type="submit">add</button>
          </form>
        </div>
      </div>
    </div>

    <div class="col-4">
      <h3>Order Summary</h3>
       <%= render "order_total_summary.html", order: @order %>
    </div>
  </div>
  </div>
</div>

avia-develop/apps/admin_app/lib/admin_app_web/templates/order/address_search.html.eex
<div class="container">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="/orders">Orders</a></li>
      <li class="breadcrumb-item active" aria-current="page"><%= @order.number %></li>
    </ol>
  </nav>

  <h2>
    Order #<%= @order.id %>
    <%= state_badge(@order.state) %>
  </h2>
  <div class="row">
    <div class="col-8">
      <div class="card">
        <div class="card-body">
          <div class="card-body">
            <form method="get">
              <input type="text" name="address_search">
            </form>
          </div>
            <div class="card-header text-center">Cart</div>
            <div class="card-body">
              <table class="table">
                <thead class="thead-light">
                  <tr>
                    <th scope="col">First Name</th>
                    <th scope="col">Last Name</th>
                    <th scope="col">Address</th>
                    <th scope="col">City</th>
                    <th scope="col">Phone</th>
                    <th scope="col">Attach</th>
                  </tr>
                </thead>
                <tbody>
                  <%= for address <- @address_list do %>
                    <%= build_address(address, @order) %>
                  <% end %>
                </tbody>
              </table>
            </div>
        </div>
      </div>
    </div>
    <div class="col-4">
      <h3>Order Summary</h3>
      <%= render "order_total_summary.html", order: @order %>
    </div>
  </div>
  </div>
</div>

avia-develop/apps/admin_app/lib/admin_app_web/templates/order/addresses.html.eex
<%= unless @order.billing_address == nil || @order.shipping_address == nil do %>
<div class="card">
  <div class="card-header text-center">Addresses</div>
  <div class="card-body row">
    <div class="col col-sm text-center">
      <h5>Billing</h5><hr>
      <%= render_address(@order.billing_address) %>
    </div>
    <div class="col col-sm text-center">
      <h5>Shipping</h5><hr>
      <%= render_address(@order.shipping_address) %>
    </div>
    <div class="col col-sm text-center">
      <h5>Shipping Method Selected</h5>
      <%= shipping_method(@order) %>
    </div>
  </div>
</div>
<% else %>
<div class="card text-center">
  <div class="card-header text-center">Addresses</div>
  <p class="card-body">
    The order is in <%= state_badge(@order.state) %> state and does not have any
    associated address.
  </p>
  <div class="card-footer">
    <a href=<%= "#{@order.number}/address/search" %>
      <button> Select Address </button></a>
    <a href=<%= "#{@order.number}/address/add" %>
      <button> Add Address </button></a>
  </div>
</div>
<% end %>

avia-develop/apps/admin_app/lib/admin_app_web/templates/order/line_item_card.html.eex
<div class="media mt-3 lineitem-detail">
   <a class="pr-3" href="#">
   <img src="/images/empty-img.png" alt="Default">
   </a>
   <div class="media-body">
      <div class="mt-0 text-capitalize name"><%= render_variant(@line_item.product) %></div>
      <div class="variant">
         <span>Quantity</span>
         <span><%= render_quantity_with_stock(@line_item) %></span>
      </div>
   </div>
</div>

avia-develop/apps/admin_app/lib/admin_app_web/templates/order/show.html.eex
<div class="list-container">
   <div class="pt-3 pb-0 pr-3 pl-3 back"> <img src="/images/left-arrow.svg"
      width="20" height="20" class="d-inline-block align-top" alt="">
      <a href="/orders">Orders </a>
   </div>
   <h4 class="p-3 m-0">Order Detail</h4>
   <div class="row m-0 order-detail lineitem">
      <div class="col-12">
        <div class="row">
            <div class="col-6">
               <h2>Order from <%= order_user_name(@order) %></h2>
               <div class="orderon"><span class="mr-2"><%= @order.number %></span> via Avia</div>
               <div class="orderon">
                <span class="mr-1"><%= order_item_count(@order) %>,</span>
                <span><%= @order_total %></span>
               </div>
            </div>
            <div class="col-6">
              <div class="row">
                <div class="col-7"></div>
                <div class="col-5">
                    <div class="orderhead">Ship Details</div>
                    <div class="orderon">Ordered <%= format_date(@order.updated_at) %></div>
                    <div class="orderon">Ship to <%= get_country_state(@order) %></div>
                </div>
              </div>
            </div>
         </div>
         <div class="my-3 order-btns">
            <div class="btn-group">
              <button class="btn btn-outline-secondary btn-md dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Order Actions
              </button>
              <div class="dropdown-menu">
                <%= link "Pending", to: order_package_path(@conn, :update_package,
                    @order.id, [state: :processing]), method: :put, class: "dropdown-item" %>
                <%= link "Ready", to: order_package_path(@conn, :update_package,
                    @order.id, [state: :ready]), method: :put, class: "dropdown-item" %>
                <%= link "Ship", to: order_package_path(@conn, :update_package,
                    @order.id, [state: :shipped]), method: :put, class: "dropdown-item" %>
                <div class="dropdown-divider"></div>
                <%= if check_for_cod(@order) do %>
                  <% cod_status = cod_status(@order)%>
                  <%= link cod_status.display, to: order_cod_update_path(@conn, :cod_payment_update,
                    @order.id, [state: cod_status.state]), method: :put, class: "dropdown-item" %>
                <% end %>
                 <%= link "Mark as Delivered", to: order_package_path(@conn, :update_package,
                    @order.id, [state: :delivered]), method: :put, class: "dropdown-item" %>
                <%= link "Mark as Complete", to: order_state_path(@conn, :update_state,
                    @order.id, [state: :complete]), method: :put, class: "dropdown-item" %>
                </div>
            </div>
         </div>
         <h3 class="mt-3">Print</h3>
         <div class="card col-12 print">
            <div class="print-sub-head">What would you like to print?</div>
            <div class="media lineitem-detail mx-3">
               <div class="media-body">
                  <a class="mt-0 text-capitalize name">Packing slips</a>
                  <div class="variant">
                    Print the packing slips for the order.
                  </div>
               </div>
               <a class="btn btn-primary float-right" style="width: 100px;" href="/orders/<%= @order.number %>/download-packing-slip" > Download </a>
            </div>
            <div class="media lineitem-detail mt-3 mx-3">
               <div class="media-body">
                  <a class="mt-0 text-capitalize name">Order Invoice</a>
                  <div class="variant">
                    Download the order invoice.
                  </div>
               </div>
               <a class="btn btn-primary float-right " style="width: 100px;" href="/orders/<%= @order.number %>/download-invoice"> Download</a>
            </div>
            <div class="media lineitem-detail mt-3 mx-3">
               <div class="media-body">
                  <a class="mt-0 text-capitalize name">Show Packing Slip</a>
                  <div class="variant">
                    Preview the packing slip.
                  </div>
               </div>
               <a class="btn btn-primary float-right " style="width: 100px;" href="/orders/<%= @order.number %>/show-packing-slip">Show</a>
            </div>
         </div>
         <h3 class="mt-3">Shipping Details</h3>
         <div class="card col-12">
            <div class="row">
               <div class="col-4">
                  <div class="address">
                     <div class="ship mb-3"> Ship to </div>
                     <%= render_address(@order.shipping_address) %>
                  </div>
               </div>
               <div class="col-8">
                  <div class="address">
                     <div class="ship mb-3"> Shipping Method Selected </div>
                     <div class="std-shipping">
                        <div class="float-left">
                          <%= shipping_method(@order) %>
                        </div>
                        <div class="float-right ship ">
                          <%= @order_total %>
                        </div>
                        <div class="clearfix"></div>
                     </div>
                     <%= for line_item <- @order.line_items do %>
                     <div class="media mt-3 lineitem-detail">
                        <a class="pr-3" href="#">
                          <img src="/images/empty-img.png" alt="Default">
                        </a>
                        <div class="media-body">
                          <div class="mt-0 text-capitalize"><%= line_item.product.name %></div>
                        </div>
                        <div class="ship" >
                          Qty <span>1</span>
                        </div>
                     </div>
                     <% end %>
                  </div>
               </div>
            </div>
         </div>
         <h3 class="mt-3">Receipt # <%= @order.number %></h3>
         <div class="card col-12">
            <div class="table-responsive mt-2">
               <table class="table">
                  <thead>
                     <tr class="d-flex">
                        <th class="col-8">Items</th>
                        <th class="col-2 text-center">Quantity</th>
                        <th class="col-2 text-right">Item Price</th>
                     </tr>
                  </thead>
                  <tbody>
                    <%= for line_item <- @order.line_items do %>
                      <tr class="d-flex">
                          <td class="col-8 text-left">
                            <div class="media lineitem-detail">
                                <a class="pr-2 mr-1" href="#" >
                                <img href="#" src="/images/empty-img.png" alt="Default">
                                </a>
                                <div class="media-body">
                                  <a class="mt-0 text-capitalize name"> <%= line_item.product.name %></a>
                                  <div class="variant">
                                  </div>
                                </div>
                            </div>
                          </td>
                          <td class="col-2"><%= line_item.quantity %></td>
                          <td class="col-2 text-right"><%= line_item.unit_price %></td>
                      </tr>
                      <tr class="d-flex">
                      <td class="col-10 text-left" colspan="2">Item Total</td><td class="col-2 text-right"><%= line_item_total(line_item) %></td>
                      </tr>
                     <% end %>
                  </tbody>
               </table>
            </div>
            <div class="row m-0 summery-datail">
                  <div class="col-6 left">
                     Shipping cost
                  </div>
                  <div class="col-6 right">
                     <%= shipping_total(@order) %>
                  </div>
               </div>
               <div class="row m-0 total">
                  <div class="col-6 left">
                     <div>Tax</div>
                     <div class="total-text">Order total</div>
                  </div>
                  <div class="col-6 right">
                     <div> <%= tax_total(@order) %> </div>
                     <div class="total-text"> <%= @order_total %></div>
                     <div class="paid-via mt-4">
                      <%= for payment <- @order.payments do %>
                        <div class="">
                            Paid via <b> <%= payment.payment_type %></b>
                        </div>
                        <div class="n-paid">
                           Status <%= payment.state %>
                        </div>
                        <% end %>
                     </div>
                  </div>
               </div>
         </div>
      </div>
</div>